export const SEND_ORDER_REQUEST: 'SEND_ORDER_REQUEST' = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_SUCCESS: 'SEND_ORDER_SUCCESS' = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAILED: 'SEND_ORDER_FAILED' = 'SEND_ORDER_FAILED';
export const IS_EMPTY: 'IS_EMPTY' = 'IS_EMPTY';
export const CLOSE_ORDER_DETAILS: 'CLOSE_ORDER_DETAILS' = 'CLOSE_ORDER_DETAILS';
