export const USER_SIGN_IN: 'USER_SIGN_IN' = 'USER_SIGN_IN';
export const USER_SIGN_OUT: 'USER_SIGN_OUT' = 'USER_SIGN_OUT';
export const USER_REGISTRATION: 'USER_REGISTRATION' = 'USER_REGISTRATION';
export const USER_UPDATE: 'USER_UPDATE' = 'USER_UPDATE';
export const USER_GET_USER_REQUEST: 'USER_GET_USER_REQUEST' = 'USER_GET_USER_REQUEST';
export const USER_GET_USER_SUCCESS: 'USER_GET_USER_SUCCESS' = 'USER_GET_USER_SUCCESS';
export const USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST' = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS' = 'USER_UPDATE_SUCCESS';
